# Generated by Django 4.1.3 on 2022-11-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homegroup',
            name='name',
            field=models.CharField(default="Alex's Kitchen", max_length=50),
            preserve_default=False,
        ),
    ]
