# Generated by Django 4.1.3 on 2022-11-27 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_recipeingredient_listingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='list',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
