# Generated by Django 4.1.3 on 2022-11-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_recipe_list_delete_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='updates',
            field=models.BigIntegerField(default=0),
        ),
    ]
