# Generated by Django 4.1.3 on 2022-12-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_list_updates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='updates',
        ),
        migrations.AddField(
            model_name='listingredient',
            name='quantity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='quantity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
